src/Entity/Shop.php
<?php

namespace App\Entity;

use App\Repository\ShopRepository;
use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShopRepository")
 */
class Shop
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $streetNumber;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postalCode;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="shop", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $products;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Menu", mappedBy="shop")
     */
    private $menus;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="shops")
     * @Assert\NotNull(message="Choisir un Utilisateur s'il-vous-plaît")
     */
    private $user_account;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Order", mappedBy="shop")
     */
    private $orders;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->menus = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getStreetNumber(): ?int
    {
        return $this->streetNumber;
    }

    public function setStreetNumber(?int $streetNumber): self
    {
        $this->streetNumber = $streetNumber;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    /**
     * @return Collection|Product[]
     */
    public function getNonDeletedProducts(): Collection
    {
        $criteria = ShopRepository::createNonDeletedCriteria();

        return $this->products->matching($criteria);
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setShop($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getShop() === $this) {
                $product->setShop(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Menu[]
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->menus->contains($menu)) {
            $this->menus[] = $menu;
            $menu->setShop($this);
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        if ($this->menus->contains($menu)) {
            $this->menus->removeElement($menu);
            // set the owning side to null (unless already changed)
            if ($menu->getShop() === $this) {
                $menu->setShop(null);
            }
        }

        return $this;
    }

    public function getUserAccount(): ?User
    {
        return $this->user_account;
    }

    public function setUserAccount(?User $user_account): self
    {
        $this->user_account = $user_account;

        return $this;
    }

    public function getAddress(): string
    {
        return $this->getStreetNumber().' '.$this->getStreet().' '.$this->getPostalCode().' '.$this->getCity();
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getImagePath()
    {
        return UploaderHelper::SHOP_IMAGE.'/'.$this->getPicture();
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setShop($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getShop() === $this) {
                $order->setShop(null);
            }
        }

        return $this;
    }
}

src/Controller/BackOwner/ProductAdminController.php
<?php

namespace App\Controller\BackOwner;

use App\Entity\Shop;
use App\Entity\User;
use App\Repository\ProductRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class ProductAdminController extends AbstractController
{
    /**
     * @Route("/admin/product", name="product_admin", methods={"POST", "GET"})
     */
    public function index(ProductRepository $repository, Request $request, PaginatorInterface $paginator, Security $security)
    {
        /** @var User $user */
        $user = $security->getUser();
//        $q = $request->query->get('q');
        $shopId = $request->query->get('id');
        $shop = $this->getDoctrine()->getRepository(Shop::class)->find($shopId);

        if ($shop->getUserAccount() != $user) {
            throw $this->createNotFoundException();
        }

//        $shops = $this->getUser()->getShops();

        $query = $repository->getProductsByShop($shop);
//        $queryBuilder = $repository->getWithSearchQueryBuilder($q);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            10/*limit per page*/
        );

        return $this->render('product_admin/index.html.twig', [
            'pagination' => $pagination,
            'shop' => $shop
        ]);
    }
}

templates/product_admin/index.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Gestion de Produits{% endblock %}

{#{% block content_class %}{{ parent() }} show-article-container-border-green{% endblock %}#}

{% block content_body %}
<section class="home-about-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Gérer vos {{ pagination.getTotalItemCount() }} Produits</h1>

                {#<form>#}
                    {#<div class="input-group mb-3">#}
                        {#<input type="text"#}
                               {#name="q"#}
                               {#class="form-control"#}
                               {#placeholder="Search..."#}
                               {#value="{{ app.request.query.get('q') }}"#}
                        {#>#}
                        {#<div class="input-group-append">#}
                            {#<button type="submit"#}
                                    {#class="btn btn-outline-secondary">#}
                                {#<span class="fa fa-search"></span>#}
                            {#</button>#}
                        {#</div>#}
                    {#</div>#}
                {#</form>#}

                <a href="{{ path('owner_product_new', {id: shop.id}) }}" class="btn btn-primary pull-right">
                    Créer <span class="fa fa-plus-circle"></span>
                </a>

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Propiétaire</th>
                        <th>Magasin</th>
                        <th>Article</th>
                        <th>Publié le </th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for product in pagination %}
                            <tr>
                                <td>
                                    {{ product.shop.userAccount.email }}
                                </td>
                                <td>
                                    {{ product.shop.name }}
                                </td>
                                {#Utiliser slice ou twig extension#}
                                <td>
                                    {{ product.name }}
                                </td>
                                <td>
                                    {{ product.createdAt|ago }}
                                </td>
                                <td>
                                    <a href="{{ path('owner_product_edit', {'id': product.id}) }}">
                                        <span class="fa fa-pencil"></span>
                                    </a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="4" class="text-center">
                                    Aucun produit trouvé
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {{ knp_pagination_render(pagination) }}

            </div>
        </div>
    </div>
</section>
{% endblock %}