src/Entity/Menu.php
<?php

namespace App\Entity;

use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MenuRepository")
 */
class Menu
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Order", inversedBy="menus")
     */
    private $orders;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Shop", inversedBy="menus")
     */
    private $shop;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Product", inversedBy="menus")
     */
    private $products;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
        }

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
        }

        return $this;
    }

    public function getImagePath()
    {
        return UploaderHelper::MENU_IMAGE.'/'.$this->getPicture();
    }
}

src/Entity/Shop.php
<?php

namespace App\Entity;

use App\Repository\ShopRepository;
use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShopRepository")
 */
class Shop
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $streetNumber;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postalCode;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="shop", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $products;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Menu", mappedBy="shop")
     */
    private $menus;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="shops")
     * @Assert\NotNull(message="Choisir un Utilisateur s'il-vous-plaît")
     */
    private $user_account;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Order", mappedBy="shop")
     */
    private $orders;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->menus = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getStreetNumber(): ?int
    {
        return $this->streetNumber;
    }

    public function setStreetNumber(?int $streetNumber): self
    {
        $this->streetNumber = $streetNumber;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    /**
     * @return Collection|Product[]
     */
    public function getNonDeletedProducts(): Collection
    {
        $criteria = ShopRepository::createNonDeletedCriteria();

        return $this->products->matching($criteria);
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setShop($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getShop() === $this) {
                $product->setShop(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Menu[]
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->menus->contains($menu)) {
            $this->menus[] = $menu;
            $menu->setShop($this);
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        if ($this->menus->contains($menu)) {
            $this->menus->removeElement($menu);
            // set the owning side to null (unless already changed)
            if ($menu->getShop() === $this) {
                $menu->setShop(null);
            }
        }

        return $this;
    }

    public function getUserAccount(): ?User
    {
        return $this->user_account;
    }

    public function setUserAccount(?User $user_account): self
    {
        $this->user_account = $user_account;

        return $this;
    }

    public function getAddress(): string
    {
        return $this->getStreetNumber().' '.$this->getStreet().' '.$this->getPostalCode().' '.$this->getCity();
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getImagePath()
    {
        return UploaderHelper::SHOP_IMAGE.'/'.$this->getPicture();
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setShop($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getShop() === $this) {
                $order->setShop(null);
            }
        }

        return $this;
    }
}

src/Controller/Front/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: bricefouepe
 * Date: 26/01/2020
 * Time: 22:30
 */

namespace App\Controller\Front;

use App\Entity\Product;
use App\Repository\OrderRepository;
use App\Repository\ProductRepository;
use App\Service\Cart\CartHelper;
use App\Service\OrderNumber;
use App\Service\Mailer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/panier", name="cart_")
 */
class CartController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(SessionInterface $session, ProductRepository $productRepository)
    {
        if (!$session->has('panier')) {
            $session->set('panier', []);
        }


        $produits = $productRepository->findArray(array_keys($session->get('panier')));

        return $this->render('cart/panier.html.twig', [
            'produits' => $produits,
            'panier' => $session->get('panier'),
        ]);
    }

    /**
     * @Route("/validation", name="validation")
     */
    public function validate(CartHelper $cartHelper, OrderRepository $orderRepository, SessionInterface $session)
    {
        $prepareOrder = $cartHelper->prepareOrder();
        $order = $orderRepository->find($prepareOrder->getContent());


        return $this->render('Cart/validation.html.twig', [
            'order' => $order,
//            'panier' => $session->get('panier')
        ]);
    }

    /**
     * @Route("/validate", name="validate")
     */
    public function validation(OrderRepository $orderRepository, SessionInterface $session, Request $request, Mailer $mailer, OrderNumber $number)
    {
        $shopId = $request->query->get('id');
        $em = $this->getDoctrine()->getManager();
        $order = $orderRepository->find($shopId);
        if (!$order || $order->getValidate() == true) {
            throw $this->createNotFoundException();
        } else {
            $order->setValidate(true);
            $order->setOrderNumber($number->orderNumber());
            $em->flush();

            $session->remove('panier');
            $session->remove('order');

            $mailer->sendOrderMessage($order);

            $this->addFlash('success', 'Votre Commande a été validé avec succès');
            return $this->redirectToRoute('user_orders_index');
        }
    }

    /**
     * @Route("/show/{id}", name="show")
     */
    public function show(Product $product, SessionInterface $session)
    {
        if (!$product) {
            throw $this->createNotFoundException();
        }

        if ($session->has('panier')) {
            $panier = $session->get('panier');
        } else {
            $panier = false;
        }

        return $this->render('Front/presentation.html.twig', [
            'product' => $product,
            'panier' => $panier
        ]);
    }

    /**
     * @Route("/add/{id}", name="add")
     */
    public function add(CartHelper $cartHelper, $id)
    {
        $cartHelper->add($id);

        return $this->redirectToRoute('cart_index', [
            'id' => $id
        ]);
    }


    /**
     * @Route("/remove/{id}", name="remove")
     */
    public function remove(CartHelper $cartHelper, $id, SessionInterface $session)
    {
        $cartHelper->remove($id);
        return $this->redirectToRoute('cart_index', [
            'id' => $id
        ]);
    }
}

src/Controller/Front/DefaultController.php
<?php

namespace App\Controller\Front;

use App\Entity\Shop;
use App\Repository\ShopRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="default_index", methods={"GET"})
     */
    public function index(): Response
    {
        return $this->render('Front/index.html.twig');
    }

    /**
     * @Route("/shops", name="default_show")
     */
    public function show(ShopRepository $shopRepository)
    {
        $shops = $shopRepository->findOpensShops();

        return $this->render('Front/magasins.html.twig', [
            'shops' => $shops
        ]);
    }

    /**
     * @Route("/shop/{id}/products", name="default_products")
     */
    public function product(Shop $shop, SessionInterface $session)
    {
        if (!($shop->getStatus() === true)) {
            throw $this->createNotFoundException();
        }
        $produits = $shop->getProducts();

        if ($session->has('panier')) {
            $panier = $session->get('panier');
        } else {
            $panier = false;
        }
        return $this->render('Front/product.html.twig', [
            'shop' => $shop,
            'products' => $produits,
            'shopId' => $shop->getId(),
            'panier' => $panier
        ]);
    }


//    public function menu(SessionInterface $session)
//    {
//        if ($session->has('panier')) {
//            $nbProducts = 0;
//        }else {
//            $nbProducts = count($session->get('panier'));
//        }
//
//        return $this->render('Front/menu.html.twig', [
//            'nbProducts' => $nbProducts
//        ]);
//    }
}

src/Controller/Front/UserAccountController.php
<?php

namespace App\Controller\Front;

use App\Controller\BaseController;
use App\Form\UserAccountFormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/account")
 */
class UserAccountController extends BaseController
{
    /**
     * @Route("/", name="app_account", methods={"GET", "POST"})
     */
    public function index(Request $request)
    {
        $user = $this->getUser();
        $form = $this->createForm(UserAccountFormType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();

            if (true === $form['agreeTerms']->getData()) {
                $user->agreeTerms();
            }

            $user->setSubscribeToNewsletter($user->subscribeToNewsletter);

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }

        return $this->render('userAccount/index.html.twig', [
            'accountForm' => $form->createView(),
        ]);
    }
}

templates/Front/base_front.html.twig
{% extends 'base.html.twig' %}

templates/Front/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<section class="banner-area relative" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row fullscreen d-flex justify-content-center align-items-center" style="height: {{652}}px";>
                <div class="banner-content col-lg-10 col-md-12 justify-content-center">
                    <h6 class="text-uppercase">Whenever we bake, bake with our heart</h6>
                    <h1>
                        Love at first bite
                    </h1>
                    <p class="text-white mx-auto">
                        Best bakery at this location.
                    </p>
                    <a href="{{ path('default_show') }}" class="primary-btn squire text-uppercase mt-10">Check Our Menu</a>
                </div>
            </div>
        </div>
</section>
{% endblock %}

templates/Front/magasins.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container" style="margin-top: 70px">
        <table>
            <div class="row">
                {% for shop in shops %}
                    <div class="col-lg-4 col-sm-6 mb-4">
                        <div class="card h-100">
                            <a href="{{ path('default_products', {id: shop.id}) }}"><img class="card-img-top" src="{{ shop.imagePath|imagine_filter('squared_thumbnail_shop') }}" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">{{ shop.name }}</a>
                                </h4>
                                <p class="card-text">{{ shop.address }}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">{{ shop.status ? 'Ouvert' : 'fermer' }}</small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </table>
    </div>
{% endblock %}

templates/Front/menu.html.twig
<div class="col-sm-3">
    <div class="card card-body bg-light">
        <table class="table table-borderless">
            <thead>
            <tr>
                <th class="text-center">Panier</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <a href="#">
                        {% if nbProducts == 0 %}
                            Aucun Produit dans le panier
                        {% elseif nbProducts == 1 %}
                            1 produit dans le panier
                        {% else %}
                            {{ nbProducts }} produits dans le panier
                        {% endif %}
                    </a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

templates/Front/presentation.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container" style="margin-top: 70px; margin-bottom: 50px;">
        <div class="card">
            <div class="row">
                <aside class="col-sm-5 border-right">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div> <a href="#"><img src=""></a></div>
                        </div> <!-- slider-product.// -->
                    </article> <!-- gallery-wrap .end// -->
                </aside>
                <aside class="col-sm-7">
                    <article class="card-body p-5">
                        <h3 class="title mb-3">{{ product.name }}</h3>

                        <p class="price-detail-wrap">
                            <span class="price h3 text-warning">
                                <span class="num">{{ product.price }}</span><span class="currency">€</span>
                            </span>
                        </p> <!-- price-detail-wrap .// -->
                        <dl class="item-property">
                            <dt>Description</dt>
                            <dd><p>{{ product.description }} </p></dd>
                        </dl>
                        <dl class="param param-feature">
                            <dt>Catégorie#</dt>
                            <dd>{{ product.category.name }}</dd>
                        </dl>  <!-- item-property-hor .// -->
                        {#<dl class="param param-feature">#}
                            {#<dt>Color</dt>#}
                            {#<dd>Black and white</dd>#}
                        {#</dl>  <!-- item-property-hor .// -->#}
                        {#<dl class="param param-feature">#}
                            {#<dt>Delivery</dt>#}
                            {#<dd>Russia, USA, and Europe</dd>#}
                        {#</dl>  <!-- item-property-hor .// -->#}

                        <hr>
                        {% if panier[product.id] is not defined %}
                            <form action="{{ path('cart_add', {id: product.id}) }}" method="GET">
                                <select name="qte" class="form-control form-control-sm" style="width:70px;">
                                    {% for i in 1..10 %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>

                                <hr>
                                {#<div class="row">#}
                                    {#<div class="col-md-offset-4 col-md-8 float-right">#}
                                        <button type="submit" class="btn btn-primary float-right">
                                            <span class="glyphicon glyphicon-shopping-cart"></span> Mettre dans le panier
                                        </button>
                                    {#</div>#}
                                {#</div>#}
                                {#<a href="{{ path('cart_add', {id: product.id}) }}" class="btn btn-success float-right">#}
                                    {#<i class="fa fa-shopping-cart mr-1"></i>#}
                                    {#Ajouter au panier#}
                                {#</a>#}
                            </form>
                        {% else %}
                            <a href="{{ path('cart_index', {id: product.id}) }}" class="btn btn-success float-righ"> le produit est deja dans le panier</a>
                        {% endif %}
                        {#<div class="row">#}
                            {#<div class="col-sm-5">#}
                                {#<dl class="param param-inline">#}
                                    {#<dt>Quantité: </dt>#}
                                    {#<dd>#}
                                        {#<select class="form-control form-control-sm" style="width:70px;">#}
                                            {#<option> 1 </option>#}
                                            {#<option> 2 </option>#}
                                            {#<option> 3 </option>#}
                                        {#</select>#}
                                    {#</dd>#}
                                {#</dl>  <!-- item-property .// -->#}
                            {#</div> <!-- col.// -->#}

                        {#</div> <!-- row.// -->#}

                    </article> <!-- card-body.// -->
                </aside> <!-- col.// -->
            </div> <!-- row.// -->
        </div>
        <!--container.//-->
    </div>

{% endblock %}

templates/Front/product.html.twig
{% extends  'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {#<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">#}
{% endblock %}

{% block body %}
    <div class="container" style="margin-top: 70px">
        <div class="row">
            {#{% include 'Front/menu.html.twig' %}#}
            <div class="col-md-9">
                <div class="row">
                    {% for product in products %}

                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#"><img class="card-img-top" src="{{ product.imagePath|imagine_filter('squared_thumbnail_shop') }}" style="height: 100%"></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <span>{{ product.name }}</span>
                                    </h4>
                                    <h5>{{ product.price }}€</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer">
                                    <a href="{{ path('cart_show', {id: product.id}) }}" class="btn btn-primary float-left">
                                        {#<i class="fa fa-shopping-cart mr-2"></i>#}
                                        infos
                                    </a>
                                    {% if panier[product.id] is not defined %}
                                        <a href="{{ path('cart_add', {id: product.id}) }}" class="btn btn-success float-right">
                                            <i class="fa fa-shopping-cart mr-1"></i>
                                            Ajouter
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}